{
 "title": "Aura",
 "description": "A dashboard for cosmos validator",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "jobs", "query": { "query": "label_values(job)" } },
   { "name": "chain", "query": "${VAR_CHAIN}" },
   { "name": "node", "query": "${VAR_NODE}" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$jobs\",label=\"$node\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Validator Power",
   "type": "timeseries",
   "description": "$node Validator Power",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_power{label=\"$node\"}",
     "legendFormat": " $node validator power"
    }
   ]
  },
  {
   "title": "connected peers",
   "type": "timeseries",
   "description": "$node connected peers",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{label=\"$node\"}",
     "legendFormat": "$node tendermint_p2p_peers "
    },
    {}
   ]
  },
  {
   "title": "latest block and last signed block",
   "type": "timeseries",
   "description": "latest block and last signed block",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "tendermint_consensus_latest_block_height{label=\"$node\"}",
     "legendFormat": "$chain lastest block"
    },
    {
     "expr": "tendermint_consensus_validator_last_signed_height{label=\"$node\"}",
     "legendFormat": "Last signed block"
    }
   ]
  },
  {
   "title": "Total missed block",
   "type": "timeseries",
   "description": "$node total missed block",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_missed_blocks{label=\"$node\"}",
     "legendFormat": "$node total missed block"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "description": "$node CPU load",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load5{label=\"$node\"}",
     "legendFormat": "5 min average CPU load "
    },
    {
     "expr": "node_load15{label=\"$node\"}",
     "legendFormat": "15 min average CPU load "
    }
   ]
  },
  {
   "title": "Free Disk",
   "type": "timeseries",
   "description": "$node Free Disk",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{label=\"$node\",fstype=\"ext4\"}"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "timeseries",
   "description": "$node Free memory",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{label=\"$node\"}+node_memory_Buffers_bytes{label=\"$node\"}+node_memory_Cached_bytes{label=\"$node\"}+node_memory_Slab_bytes{label=\"$node\"}",
     "legendFormat": "$node free memory"
    }
   ]
  }
 ]
}